[workspace]
members = [
    "drmem-api",
    "drmem-config",
    "drivers/*",
    "backends/drmem-db-simple",
    "drmemd"
]
exclude = ["backends/drmem-db-redis"]

# Profiles used by all binaries and packages.

[profile.release]
opt-level = 3
debug = false
lto = "thin"
debug-assertions = false
strip = "debuginfo"
