[package]
name = "engine"
version = "0.1.0"
authors = ["Rich Neswold <rich.neswold@gmail.com>"]
edition = "2018"

# See more keys and their definitions at
# https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "^2"
toml = "0.5.6"
palette = "0.5"
huebridge = "0.3.0"
redis = { version = "0.17.0", features = ["aio", "tokio-rt-core"] }
tracing-subscriber = "^0.2"
tracing-futures = "^0.2"
tracing = { version = "^0.1", features = ["log"] }
tokio = { version = "0.2", features = ["rt-threaded", "macros", "time"] }
log = { version = "0.4", features = []}

[profile.release]
opt-level = 3
debug = false
lto = true
debug-assertions = false
