[workspace]
members = ["drmem-api", "drmem-config", "drivers/*", "backends/*", "drmemd"]

# Profiles used by all binaries and packages.

[profile.release]
opt-level = 3
debug = false
lto = true
debug-assertions = false
