[package]
name = "drmem-db-simple"
authors = ["Rich Neswold <rich.neswold@gmail.com>"]
version = "0.1.0"
edition = "2021"
description = "Simple backend for DrMem control system"
homepage = "https://github.com/rneswold/drmem"
repository = "https://github.com/rneswold/drmem"
license = "BSD-3-Clause"
publish = false
categories = ["embedded"]
keywords = ["control-system", "automation"]

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
async-trait = "0.1"
drmem-api = { path = "../../drmem-api", version = "0.1" }
tokio = { version = "1", features = ["sync"] }
tracing = { version = "^0.1", features = ["std"] }

[dependencies.drmem-config]
path = "../../drmem-config"
version = "0.1"
