[package]
name = "drmem-api"
version = "0.1.0"
authors = ["Rich Neswold <rich.neswold@gmail.com>"]
edition = "2021"
description = "Traits and types used internally by the DrMem control system"
homepage = "https://github.com/DrMemCS/drmem"
repository = "https://github.com/DrMemCS/drmem"
license = "MIT"
categories = ["embedded"]
keywords = ["control-system", "automation"]

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
toml = "0.5.6"
async-trait = "0.1"
tokio = { version = "1", features = ["sync"] }
tokio-stream = { version = "0.1" }
serde = "1.0.115"
serde_derive = "1.0.115"
