[package]
name = "drmemd"
version = "0.1.0"
authors = ["Rich Neswold <rich.neswold@gmail.com>"]
edition = "2021"
description = "Main process of the DrMem control system"
homepage = "https://github.com/rneswold/drmem"
repository = "https://github.com/rneswold/drmem"
license = "BSD-3-Clause"
publish = false
categories = ["embedded", "hardware-support"]
keywords = ["control-system", "automation"]

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
toml = "0.5.6"
tracing-subscriber = "^0.2"
tracing-futures = "^0.2"
tracing = { version = "^0.1", features = ["std"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time"] }
tokio-stream = { version = "0.1", features = ["sync", "net"] }
futures = "0.3"

drmem-api = { path = "../drmem-api", version = "0.1" }
drmem-config = { path = "../drmem-config", version = "0.1" }

# This section defines the driver dependencies. Most drivers are
# optional, but a few drivers define common devices for a `drmem`
# installation.

[dependencies.drmem-drv-sump]
path = "../drivers/drmem-drv-sump"
version = "0.1"
optional = true

[dependencies.drmem-drv-ntp]
path = "../drivers/drmem-drv-ntp"
version = "0.1"
optional = true

[dependencies.drmem-drv-weather-wu]
path = "../drivers/drmem-drv-weather-wu"
version = "0.1"
optional = true

# This section defines the optional dependencies for backend storage.

[dependencies.drmem-db-redis]
path = "../backends/drmem-db-redis"
version = "0.1"
optional = true

[dependencies.drmem-db-simple]
path = "../backends/drmem-db-simple"
version = "0.1"
optional = true

# This section defines the optional dependencies for the 'graphql'
# feature.

[dependencies.juniper]
version = "0.15"
optional = true

[dependencies.chrono]
version = "0.4"
optional = true

[dependencies.juniper_warp]
version = "0.7"
features = ["subscriptions"]
optional = true

[dependencies.juniper_graphql_ws]
version = "0.3"
optional = true

[dependencies.warp]
version = "0.3"
optional = true

# These are features that can be enabled for drmem.

[features]
default = ["simple-backend"]

# Backends

simple-backend = ["drmem-db-simple"]
redis-backend = ["drmem-db-redis"]

# Client APIs

graphql = ["chrono", "warp", "juniper", "juniper_graphql_ws", "juniper_warp"]

# Drivers

driver-ntp = ["drmem-drv-ntp"]
driver-sump = ["drmem-drv-sump"]
driver-weather-wu = ["drmem-drv-weather-wu"]
