name: CI

on:
  workflow_dispatch:
  push:
    branches: [ "main", "pr-*" ]
  pull_request:
    branches: [ "main", "pr-*" ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test --verbose --features graphql
